### ISSUE TITLE
Back buttons are confusing/misleading

### ISSUE THREAD

**Issue by o-farag** [Lenscrafters-Capstone/LensCrafters-free#17]
The back buttons make it seem like you're going back to what the text beside them displays

This makes it feel like we're going back to selecting lens materials and aren't actually on that page
![image](https://github.com/Lenscrafters-Capstone/LensCrafters-free/assets/15898988/bf91d68e-a749-43a0-bdd0-527ac4fa897f)

This makes it feel like we're going back to visualizing our glasses
![image](https://github.com/Lenscrafters-Capstone/LensCrafters-free/assets/15898988/6b7bcbb9-3024-4f0a-90ec-6e56db562e4c)

I think the title should be clearly differentiated from the back button, and maybe the back button could also have the page we're going back to.

**Comment by JessicaJHee** [comment]
I see how that can be misleading, what do you think about this approach: 

How LensCrafters site does it:
<img width="617" alt="image" src="https://github.com/Lenscrafters-Capstone/LensCrafters-free/assets/73968480/ca3d64b4-63ac-44d6-ade6-9c2e8d228c6b">

We could have a progress bar that gives the user an idea of how far along they are in the workflow and also differentiates the back button. I'm not sure about adding the title of the page we're going back to since that can look messy.

**Comment by o-farag** [comment]
Yea I think that's much better. Honestly as long as the arrow is separate from the text it should be easier to understand. The progress bar is cool :)

**Comment by JessicaJHee** [comment]
Closed with #25
